# Hey dude, shouldn't the configuration of a YAML file look like such
CREDENTIALS:
  ACCESS_TOKEN: USER_ACCESS_TOKEN
  CLIENT_SECRET: "USER_CLIENT_SECRET"
SLEEPTIME: 1

# The file you showed kind of looks like JSON, which is dope, but not YAML
